#!/usr/bin/env bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

$HOME/.config/yabai/create_spaces.sh

# ===== Tiling setting =========================
yabai -m config layout bsp
yabai -m config external_bar               all:39:0     \
                window_border              on           \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.10         \
                active_window_opacity      1.0          \
                normal_window_opacity      0.85         \
                window_border_width        1            \
                window_border_hidpi        off          \
                window_border_radius       11           \
                window_animation_duration  0.15         \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff2a2f38   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                20           \
                bottom_padding             10           \
                left_padding               10           \
                right_padding              10           \
                window_gap                 8
# === sketchybar ===
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

lalt - space : yabai -m window --toggle float; sketchybar --trigger window_focus
shift + lalt - f : yabai -m window --toggle zoom-fullscreen; sketchybar --trigger window_focus
lalt - f : yabai -m window --toggle zoom-parent; sketchybar --trigger window_focus
shift + lalt - 1 : yabai -m window --space 1 && sketchybar --trigger windows_on_spaces

# === apps ===
yabai -m rule --add app="^(LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off


# === apps in spaces ===
yabai -m rule --add app=Discord space=^1
yabai -m rule --add app=Spotify space=^2
yabai -m rule --add app=Safari  space=^3
yabai -m rule --add app=Xcode   space=^4
yabai -m rule --add app=iTerm2  space=^5

# === app border ===
yabai -m rule --add app="^(Discord|Spotify|Safari|Xcode)$" border=off

# === app opacity ===
yabai -m rule --add app=Discord opacity=0.96
yabai -m rule --add app=Spotify opacity=0.97
yabai -m rule --add app=Safari  opacity=0.94
yabai -m rule --add app=Xcode   opacity=0.96
